a = int(input())
b, c, d, e = input().split()
b = int(b)
c = int(c)
d = int(d)
e = int(e)

print(int(a>b), and=" ")
print(int(a>c), and=" ")
print(int(a>d), and=" ")
print(int(a>e), and=" ")